# Generated by Django 4.1.7 on 2023-04-03 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_dish_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cooks',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
