# Generated by Django 4.1.7 on 2023-04-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0006_dish_cooks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="ingredients",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="dishes",
            field=models.ManyToManyField(
                related_name="ingredients", to="restaurant.dish"
            ),
        ),
        migrations.DeleteModel(
            name="DishIngredient",
        ),
    ]
